2025-09-03 17:18:43,209 - src.meeting_room_mcp.shared.database - ERROR - 데이터베이스 초기화 실패: (pymysql.err.OperationalError) (1045, "Access denied for user 'meeting_user'@'localhost' (using password: YES)")
(Background on this error at: https://sqlalche.me/e/20/e3q8)
